server:
  port: ${PORT:8082}

spring:
  datasource:
    # Usar la misma DB en memoria 'orders' (la consola debe usar EXACTAMENTE esta URL)
    url: ${DEV_DB_URL:jdbc:h2:mem:orders;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    driver-class-name: org.h2.Driver
    username: ${DEV_DB_USER:sa}
    password: ${DEV_DB_PASS:}
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

feature:
  enableDebug: true
